name: PyPI Release

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for trusted publishing
  contents: read

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false  # Only run for full releases
    environment:
      name: pypi
      url: https://pypi.org/project/django-manifeststaticfiles-enhanced/
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true