name: Test PyPI Release

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering for testing

permissions:
  id-token: write  # Required for trusted publishing
  contents: read

jobs:
  test-pypi-publish:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == true  # Only run for pre-releases
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/django-manifeststaticfiles-enhanced/
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true